# golangci-lint configuration for VC Stack
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - bodyclose
    - gocognit
    - godot
    - goprintffuncname
    - nolintlint
    - whitespace
  disable:
    - unparam
    - revive
    - stylecheck
    - typecheck  # Disabled due to CGO_ENABLED=0 causing false positives

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 30

  gocognit:
    min-complexity: 50

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnecessaryBlock
      - rangeValCopy
      - hugeParam
      - octalLiteral
      - appendCombine
      - ifElseChain
      - typeAssertChain

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true

  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G204  # Subprocess launched with variable
      - G107  # Potential HTTP request with variable url
      - G301  # Directory permissions
      - G302  # File permissions
      - G304  # File inclusion via variable
    config:
      G306: "0644"

issues:
  exclude-files:
    - "rbd_manager\\.go$"
  exclude-dirs:
    - vendor
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocognit

    # Exclude CGO-dependent files (Ceph RBD)
    - path: "rbd_manager\\.go"
      linters:
        - typecheck
        - all

    # Exclude Sentry SDK files (typecheck fails with CGO_ENABLED=0)
    - path: pkg/sentry/.*\.go
      linters:
        - typecheck

    # Exclude JWT authentication files (typecheck fails with CGO_ENABLED=0)
    - path: internal/controlplane/identity/service\.go
      linters:
        - typecheck

    - path: internal/controlplane/middleware/auth\.go
      linters:
        - typecheck

    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow warnings for err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Exclude unparam warnings - often false positives or design decisions
    - text: "."
      linters:
        - unparam

    # Exclude revive stuttering warnings - often intentional for clarity
    - text: "stutters"
      linters:
        - revive

    # Exclude godot warnings for comments - often false positives
    - text: "Comment should end in a period"
      linters:
        - godot

    # Exclude errcheck for intentionally ignored errors (marked with _)
    - text: "Error return value.*is not checked"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
