# golangci-lint configuration for VC Stack
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - pkg/sentry
  skip-files:
    - ".*rbd_manager\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - unparam
    - revive
    - bodyclose
    - gocognit
    - godot
    - goprintffuncname
    - nolintlint
    - stylecheck
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true

  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
    config:
      G306: "0644"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocognit

    # Exclude CGO-dependent files
    - path: rbd_manager\.go
      linters:
        - typecheck

    # Exclude Sentry SDK files
    - path: pkg/sentry/
      linters:
        - typecheck

    # Exclude JWT authentication files
    - path: internal/controlplane/identity/service\.go
      linters:
        - typecheck

    - path: internal/controlplane/middleware/auth\.go
      linters:
        - typecheck

    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude shadow warnings for err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
