linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - gocyclo
    - gosec
    - unconvert
    - revive
    - bodyclose
    - gocognit
    - godot
    - nolintlint
    - whitespace

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 50
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true

issues:
  exclude-files:
    - ".*rbd_manager\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocognit
