ALTER TABLE instances ADD COLUMN IF NOT EXISTS node_address VARCHAR(255);
ALTER TABLE instances ADD COLUMN IF NOT EXISTS root_disk_gb INTEGER DEFAULT 0;
ALTER TABLE instances ADD COLUMN IF NOT EXISTS user_data TEXT;
ALTER TABLE instances ADD COLUMN IF NOT EXISTS ssh_key TEXT;
ALTER TABLE instances ADD COLUMN IF NOT EXISTS enable_tpm BOOLEAN DEFAULT false;
ALTER TABLE instances ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE instances ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMP;
