apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vc-stack.fullname" . }}-secrets
  labels:
    {{- include "vc-stack.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ default (randAlphaNum 64) .Values.management.jwtSecret | b64enc | quote }}
  db-password: {{ default (randAlphaNum 32) .Values.postgresql.auth.password | b64enc | quote }}
