package host

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

// generateInstallScript returns a shell script that automates compute node setup.
// Query params: zone_id, cluster_id, port (optional, default 8081)
func (s *Service) generateInstallScript(c *gin.Context) {
	controllerURL := s.externalURL
	if controllerURL == "" {
		// Fallback: derive from request
		scheme := "http"
		if c.Request.TLS != nil {
			scheme = "https"
		}
		controllerURL = fmt.Sprintf("%s://%s", scheme, c.Request.Host)
	}

	zoneID := c.DefaultQuery("zone_id", "")
	clusterID := c.DefaultQuery("cluster_id", "")
	port := c.DefaultQuery("port", "8081")

	script := fmt.Sprintf(`#!/bin/bash
# VC Stack Compute Node Install Script
# Generated by vc-management
set -euo pipefail

CONTROLLER_URL="%s"
ZONE_ID="%s"
CLUSTER_ID="%s"
AGENT_PORT="%s"
INSTALL_DIR="/opt/vc-stack"
BIN_DIR="${INSTALL_DIR}/bin"
CONF_DIR="${INSTALL_DIR}/configs"
SERVICE_NAME="vc-compute"

echo "============================================="
echo "  VC Stack Compute Node Installer"
echo "============================================="
echo "Controller: ${CONTROLLER_URL}"
echo ""

# ── Step 1: Detect OS ──────────────────────────
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS_ID="${ID}"
        OS_VERSION="${VERSION_ID}"
    else
        echo "[ERROR] Cannot detect OS. /etc/os-release not found."
        exit 1
    fi
}
detect_os
echo "[INFO] Detected OS: ${OS_ID} ${OS_VERSION}"

# ── Step 2: Install dependencies ───────────────
echo "[INFO] Installing dependencies..."
case "${OS_ID}" in
    debian|ubuntu)
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y -qq qemu-kvm libvirt-daemon-system libvirt-clients \
            qemu-utils curl jq >/dev/null 2>&1
        systemctl enable --now libvirtd
        ;;
    rhel|centos|rocky|almalinux|fedora)
        dnf install -y -q qemu-kvm libvirt libvirt-client \
            qemu-img curl jq >/dev/null 2>&1
        systemctl enable --now libvirtd
        ;;
    *)
        echo "[WARN] Unsupported OS '${OS_ID}'. Attempting generic install..."
        ;;
esac
echo "[OK] Dependencies installed."

# ── Step 3: Create directories ─────────────────
mkdir -p "${BIN_DIR}" "${CONF_DIR}"
mkdir -p /var/lib/vc-compute/configs /var/lib/vcstack/images /var/lib/vcstack/volumes
echo "[OK] Directories created."

# ── Step 4: Download vc-compute binary ─────────
echo "[INFO] Downloading vc-compute from controller..."
ARCH=$(uname -m)
case "${ARCH}" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
esac

DOWNLOAD_URL="${CONTROLLER_URL}/api/v1/artifacts/vc-compute?arch=${ARCH}"
if curl -sSfL -o "${BIN_DIR}/vc-compute" "${DOWNLOAD_URL}" 2>/dev/null; then
    chmod +x "${BIN_DIR}/vc-compute"
    echo "[OK] vc-compute downloaded."
else
    echo "[WARN] Could not download binary from controller."
    echo "       Please copy vc-compute to ${BIN_DIR}/vc-compute manually."
    echo "       Then re-run this script or start the service manually."
fi

# ── Step 5: Generate configuration ─────────────
NODE_IP=$(hostname -I | awk '{print $1}')
NODE_NAME=$(hostname -s)

cat > "${CONF_DIR}/vc-compute.env" <<ENVEOF
# VC Stack Compute Node Configuration
# Auto-generated by install script

# Controller connection
CONTROLLER_URL=${CONTROLLER_URL}

# Node identity
VC_COMPUTE_PORT=${AGENT_PORT}
NODE_NAME=${NODE_NAME}

# Zone / Cluster assignment
ZONE_ID=${ZONE_ID}
CLUSTER_ID=${CLUSTER_ID}

# Database (optional, for local state)
# DB_HOST=localhost
# DB_NAME=vcstack
# DB_USER=vcstack
# DB_PASS=

# Hypervisor
# QEMU_RUN_DIR=/var/run/vc-compute
# QEMU_CFG_DIR=/etc/vc-compute/vms

# Ceph/RBD (enable if using distributed storage)
# CEPH_ENABLED=false
# CEPH_DEFAULT_POOL=vcstack-images
# CEPH_VOLUMES_POOL=vcstack-volumes

# OVN networking (set SB address to enable SDN)
# NETWORK_OVN_SB_ADDRESS=tcp:<ovn-central-ip>:6642
# NETWORK_ENCAP_IP=${NODE_IP}
ENVEOF
echo "[OK] Configuration written to ${CONF_DIR}/vc-compute.env"

# ── Step 6: Create systemd service ─────────────
cat > /etc/systemd/system/${SERVICE_NAME}.service <<SVCEOF
[Unit]
Description=VC Stack Compute Node
After=network-online.target libvirtd.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-${CONF_DIR}/vc-compute.env
ExecStart=${BIN_DIR}/vc-compute server
WorkingDirectory=${INSTALL_DIR}
Restart=on-failure
RestartSec=5s
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable ${SERVICE_NAME}
echo "[OK] Systemd service created."

# ── Step 7: Start the service ──────────────────
systemctl start ${SERVICE_NAME}
echo "[OK] ${SERVICE_NAME} started."

# ── Step 8: Auto-register with controller ──────
echo "[INFO] Registering node with controller..."
sleep 2

CPU_CORES=$(nproc)
RAM_MB=$(awk '/MemTotal/ {printf "%%d", $2/1024}' /proc/meminfo)
DISK_GB=$(df -BG / | tail -1 | awk '{gsub(/G/,""); print $2}')
KERNEL=$(uname -r)
QEMU_VER=$(qemu-system-x86_64 --version 2>/dev/null | head -1 | grep -oP '[\d.]+' | head -1 || echo "unknown")

REG_BODY=$(cat <<REGEOF
{
  "name": "${NODE_NAME}",
  "hostname": "${NODE_NAME}",
  "ip_address": "${NODE_IP}",
  "management_port": ${AGENT_PORT},
  "host_type": "compute",
  "hypervisor_type": "kvm",
  "hypervisor_version": "${QEMU_VER}",
  "cpu_cores": ${CPU_CORES},
  "ram_mb": ${RAM_MB},
  "disk_gb": ${DISK_GB},
  "agent_version": "installer",
  "labels": {"kernel": "${KERNEL}", "os": "${OS_ID} ${OS_VERSION}", "arch": "${ARCH}"}
}
REGEOF
)

# Add zone_id / cluster_id if specified
if [ -n "${ZONE_ID}" ]; then
    REG_BODY=$(echo "${REG_BODY}" | jq --arg z "${ZONE_ID}" '. + {zone_id: ($z | tonumber)}')
fi
if [ -n "${CLUSTER_ID}" ]; then
    REG_BODY=$(echo "${REG_BODY}" | jq --arg c "${CLUSTER_ID}" '. + {cluster_id: ($c | tonumber)}')
fi

RESPONSE=$(curl -sS -X POST -H "Content-Type: application/json" \
    -d "${REG_BODY}" \
    "${CONTROLLER_URL}/api/v1/hosts/register" 2>&1) || true

if echo "${RESPONSE}" | jq -e '.uuid' >/dev/null 2>&1; then
    HOST_UUID=$(echo "${RESPONSE}" | jq -r '.uuid')
    echo "[OK] Node registered successfully! UUID: ${HOST_UUID}"
else
    echo "[WARN] Registration response: ${RESPONSE}"
    echo "       The node will retry registration on next heartbeat."
fi

echo ""
echo "============================================="
echo "  Installation Complete!"
echo "============================================="
echo "  Node IP:   ${NODE_IP}"
echo "  Agent Port: ${AGENT_PORT}"
echo "  Config:    ${CONF_DIR}/vc-compute.env"
echo "  Service:   systemctl status ${SERVICE_NAME}"
echo "  Logs:      journalctl -u ${SERVICE_NAME} -f"
echo "============================================="
`, controllerURL, zoneID, clusterID, port)

	c.Data(http.StatusOK, "text/x-shellscript; charset=utf-8", []byte(script))
}
